CREATE DATABASE rentHouseSys

CREATE TABLE `host` (
id INT PRIMARY KEY AUTO_INCREMENT,
`name` VARCHAR(10) NOT NULL DEFAULT '',
phone VARCHAR(11) NOT NULL DEFAULT '',
`count` INT NOT NULL DEFAULT 0)
SELECT * FROM HOST

INSERT INTO `host` VALUES(NULL,'张伟荣','18392',0)
INSERT INTO HOST VALUES(NULL,'刘德才','13288',0)
UPDATE HOST SET NAME='黄伟荣',phone='18191' WHERE id =3
DELETE FROM HOST WHERE id=3

SHOW TABLE STATUS FROM renthousesys

CREATE TABLE house(
id INT PRIMARY KEY AUTO_INCREMENT,
address VARCHAR(10) NOT NULL DEFAULT '',
state VARCHAR(5) NOT NULL DEFAULT '',
rent INT NOT NULL DEFAULT 0,
isPublish BOOLEAN NOT NULL DEFAULT FALSE)

INSERT INTO house VALUES(NULL,'番禺区','未出租',500,FALSE)

SELECT * FROM house

CREATE TABLE `user` (
`name` VARCHAR(10) NOT NULL DEFAULT 'admin',
`password` VARCHAR(10) NOT NULL DEFAULT 'admin')

INSERT INTO USER VALUES('libin','libin')
INSERT INTO USER VALUES('admin','admin')

SELECT * FROM USER
SHOW TABLE STATUS FROM renthousesys

CREATE TABLE houseInfo(
id INT PRIMARY KEY AUTO_INCREMENT,
hostId INT ,
houseId INT ,
FOREIGN KEY (hostId) REFERENCES HOST(id),
FOREIGN KEY (houseId) REFERENCES house(id))
SELECT * FROM houseInfo

INSERT INTO houseInfo VALUES(NULL,2,1)
INSERT INTO houseInfo VALUES(NULL,3,2)

CREATE TABLE message(
id INT PRIMARY KEY AUTO_INCREMENT,
customerName VARCHAR(10),
phone VARCHAR(11),
message VARCHAR(255),
houseInfoId INT,
localDateTime DATETIME,
FOREIGN KEY (houseInfoId) REFERENCES houseInfo(id))

ALTER TABLE message ADD COLUMN isRead BOOLEAN DEFAULT FALSE AFTER localDatetime

ALTER TABLE message DROP COLUMN isRead

SELECT * FROM message


INSERT INTO message VALUES(NULL,'欧小欣','18199','有没有家电',1,NOW())

UPDATE message SET customerName='叶婷婷',phone='19988',message='有没有空调',houseInfoId=5,localDateTime='2022-06-03 22:55:17.854',isRead=FALSE WHERE id =

INSERT INTO message VALUES(NULL,'叶婷婷','19988','有没有空调','5','2022-06-03 22:55:17.854',FALSE);